# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# Description:
#   Packages containing tests for the Checkers framework.

test_suite(
    name = "small_tests",
    tags = ["small"],
    visibility = ["//:__pkg__"],
)

py_test(
    name = "checkers_test",
    size = "small",
    srcs = ["checkers_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "context_test",
    size = "small",
    srcs = ["context_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "modules_test",
    size = "small",
    srcs = ["modules_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "parameterization_test",
    size = "small",
    srcs = ["parameterization_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "registry_test",
    size = "small",
    srcs = ["registry_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "test_case_test",
    size = "small",
    srcs = ["test_case_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "test_result_test",
    size = "small",
    srcs = ["test_result_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "test_run_test",
    size = "small",
    srcs = ["test_run_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "test_suite_test",
    size = "small",
    srcs = ["test_suite_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

py_test(
    name = "test_test",
    size = "small",
    srcs = ["test_test.py"],
    visibility = ["//:__pkg__"],
    deps = [
        "//checkers",
        "//checkers/runners/pyunit",
    ],
)

